### ISSUE TITLE
This Version of macOS is Unsupported on this Platform

### ISSUE THREAD

**Issue by Kameechewa** [dortania/Opencore-Legacy-Patcher#18]
I have a MacBook Pro 7,1 and version 0.0.6 is spoofing it as 11,1. When trying to boot the EFI to install Big Sur it tells me this Mac is not supported. I don't know what I'm doing wrong.

**Comment by jaybanger1** [comment]
You need to boot from the USB, it will show up as EFI when you hold down the option key. After you choose it, you will be printed with the “picker” there choose your boot volume.

**Comment by Kameechewa** [comment]
That’s why I’m confused. I did boot from the flash drive and it still gave me that error. I’ll try again tomorrow and list the steps I took as well as maybe make a video.

**Comment by Kameechewa** [comment]
So I have redone this process using version 0.0.7 (at least that's what the patcher reports when I run it now).

1. Use gibMacOS to download Big Sur
2. Use Disk Utility to format a 128GB flashdrive as Mac OS Extended (Journaled)
3. Extract the installer
4. Run this code <sudo /Applications/Install\ macOS\ Big\ Sur.app/Contents/Resources/createinstallmedia --volume /Volumes/MyVolume>
5. Open the Legacy Patcher
6. Change SMBIOS to MacBookPro7,1
7. Build OpenCore
8. Install it to the flashdrive using the Patcher Utility
9. Boot into the flashdrives EFI partition by holding the Option Key on the Mac
10. Get the error about this Mac not being supported

Attached you will find the EFI folder created by the patcher.
[EFI.zip](https://github.com/dortania/Opencore-Legacy-Patcher/files/5677282/EFI.zip)

**Comment by Kameechewa** [comment]
Version 0.0.8 seems to have resolved my issue

**Comment by Kameechewa** [comment]
@khronokernel @dhinakg any ideas? I'm sorry to mention you like this but I've been stuck for a while and tried dozens of time. In my above mentioned Issue #28 where I incorrectly used the model MacBookPro3,1 I was able to actually get it to boot the EFI, install, and setup. However, when doing it with my Macs actual model it doesn't work, telling me the computer isn't supported.

**Comment by khronokernel** [comment]
Mac-189A3D4F975D5FFC is MacBookPro11,1, which is supported in Big Sur. Are you able to send me a SMBIOS dump from UEFI? Wondering if the SMBIOS table is somewhat corrupt.

Steps:

1. Boot OpenCore
2. At OpenCore's picker, press spacebar
3. Select the UEFI Shell entry
4. Press `fs0:` and then `dir` to check that it's your USB's EFI partition(there will be an EFI folder). If not, cycle through `fs1:`, `fs2:`, etc till you find the USB's EFI partition with the EFI folder
5. Next run `smbiosview > fs0:\smbios.txt`(make sure to replace `fs0:` with the actual drive you're using)
6. Boot a known working OS and mount the USB's EFI([MountEFI](https://github.com/corpnewt/MountEFI) will do the job)
7. Send me the smbios.txt file you generated earlier

**Comment by Kameechewa** [comment]
Thank you so much for replying! Hopefully I did everything correctly. I ran through all of the "fs" things and only fs0 had an EFI.

[smbios.txt](https://github.com/dortania/Opencore-Legacy-Patcher/files/5720360/smbios.txt)
![01E199EB-23B4-40AE-9FE9-25641762E12E_1_102_o](https://user-images.githubusercontent.com/3394096/102702883-54e22380-422d-11eb-8826-45537390c3b1.jpeg)

**Comment by khronokernel** [comment]
Is this macOS 11.1 or 11.0.1?

**Comment by Kameechewa** [comment]
I am attempting to install 11.0.1

**Comment by khronokernel** [comment]
Try 11.1, this issue should be resolved there

**Comment by Kameechewa** [comment]
I will attempt that tonight and report back, than you.

**Comment by Kameechewa** [comment]
> Try 11.1, this issue should be resolved there

Unfortunately 11.1 has not resolved my issue. I get the exact same error message. Is there something I should try resetting?

**Comment by khronokernel** [comment]
Resolved in main
