### ISSUE TITLE
Mac15,1 5K - "An error occurred loading the update." when upgrading from Big Sur

### ISSUE THREAD

**Issue by kevwkev** [dortania/OpenCore-Legacy-Patcher#786]
### Machine Model

iMac15,1

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Other/Non-Applicable

### What is the Issue?

Using the latest release 0.3.1 because after installing nightly build 0.3.2 to USB, there is no "EFI boot" icon when holding [option] key on startup. 
Installed 0.3.1 to USB, has "EFI boot" icon, able to boot into Monterey installation screen, procced to upgrade from Big Sur, the installation will fail at about 13 minutes remaining with error "An error occurred loading the update."

**Comment by khronokernel** [comment]
This issue is resolved in 0.3.2 so unsure why you're filling against this instead of the 0.3.2 boot issues.

Regardless, what commit of 0.3.2 did you use? If your firmware is not showing an EFI Boot option with 0.3.2, that means it's failing to pick up the `boot.efi` entry on the root of the ESP:

<img width="1223" alt="Screen Shot 2021-12-11 at 10 12 07 AM" src="https://user-images.githubusercontent.com/48863253/145685449-ea9f4ad2-34f1-4b14-ac71-becb80aaf4f5.png">

Is your system running the latest firmware? Did you clear NVRAM? Where there other USB boot devices plugged in at the same time? etc

**Comment by kevwkev** [comment]
> This issue is resolved in 0.3.2 so unsure why you're filling against this instead of the 0.3.2 boot issues.
> 
> 
> 
> Regardless, what commit of 0.3.2 did you use? If your firmware is not showing an EFI Boot option with 0.3.2, that means it's failing to pick up the `boot.efi` entry on the root of the ESP:
> 
> 
> 
> <img width="1223" alt="Screen Shot 2021-12-11 at 10 12 07 AM" src="https://user-images.githubusercontent.com/48863253/145685449-ea9f4ad2-34f1-4b14-ac71-becb80aaf4f5.png">
> 
> 
> 
> Is your system running the latest firmware? Did you clear NVRAM? Were there other USB boot devices plugged in at the same time? etc

Thanks for the information. I can get the EFI boot logo to show up now after doing a NVRAM reset. Have unplugged all USB devices except the bootable install USB thumb drive. But I am still getting the same error message "an error occurred installing the update." at 13 minutes remaining.

The primary OS drive is a OWA Aura PRO X2 Nvme SSD instead of the original Apple SSD, not sure if the issue is related to this.

**Comment by kevwkev** [comment]
Yes it should be running the latest version, check updates in Big Sur, and there aren't any updates.

**Comment by kevwkev** [comment]
Error logs
========
Dec 11 20:18:29 Kevins-iMac osinstallersetupd[259]: Failed to supply bytes
Dec 11 20:18:29 Kevins-iMac osinstallersetupd[259]: Finished extracting: failed
Dec 11 20:18:29 Kevins-iMac osinstallersetupd[259]: Operation queue failed with error: Error Domain=com.apple.OSInstallerSetup.error Code=1004 "An error occurred loading the update." UserInfo={NSLocalizedDescription=An error occurred loading the update., NSUnderlyingError=0x600002eefde0 {Error Domain=SZExtractorErrorDomain Code=2 "CRC mismatch; got: 0x6088fc57 expected: 0xcef3be63 for file AssetData/payloadv2/payload.007" UserInfo={NSLocalizedDescription=CRC mismatch; got: 0x6088fc57 expected: 0xcef3be63 for file AssetData/payloadv2/payload.007, SZExtractorFileOffsetErrorKey=9822346914, SZExtractorSourceFileLineErrorKey=1346, NSFilePath=AssetData/payloadv2/payload.007, SZExtractorFunctionNameErrorKey=-[StreamingUnzipper _supplyBytes:length:withReply:]}}}
Dec 11 20:18:29 Kevins-iMac powerd[44]: Assertion Released. Type:NoIdleSleepAssertion Name:'OSInstaller Setup' Id:0x100008049 Process:osinstallersetupd [System: PrevIdle DeclUser kDisp]
Dec 11 20:18:29 Kevins-iMac powerd[44]: Assertion Released. Type:NoIdleSleepAssertion Name:'OSInstaller Setup' Id:0x100008048 Process:InstallAssistant [System: DeclUser kDisp]
Dec 11 20:18:29 Kevins-iMac InstallAssistant[255]: Stopped operation queue with Error Domain=com.apple.OSInstallerSetup.error Code=1004 "An error occurred loading the update." UserInfo={NSLocalizedDescription=An error occurred loading the update., NSUnderlyingError=0x600000f5bfc0 {Error Domain=SZExtractorErrorDomain Code=2 "CRC mismatch; got: 0x6088fc57 expected: 0xcef3be63 for file AssetData/payloadv2/payload.007" UserInfo={SZExtractorFunctionNameErrorKey=-[StreamingUnzipper _supplyBytes:length:withReply:], SZExtractorFileOffsetErrorKey=9822346914, SZExtractorSourceFileLineErrorKey=1346, NSFilePath=AssetData/payloadv2/payload.007, NSLocalizedDescription=CRC mismatch; got: 0x6088fc57 expected: 0xcef3be63 for file AssetData/payloadv2/payload.007}}}

**Comment by kevwkev** [comment]
Issue has been resolved. I redownloaded and created the install media and uninstalled Objective-See Lulu. The installation has completed successfully.
